[options]
admin_passwd = $pbkdf2-sha512$600000$vtd6b02pdc6Zk5Jybg2BEA$pBqaiCl4lNMlaIYoAmmk.nrQ0hChqAaJHGLQ4ICiwTQaDWYUNY4SmSLuNL7RJFI4/gcWad1zLG1dXdIYJgeZQQ
addons_path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

